# Generated by Django 5.1.11 on 2025-08-30 19:56

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brand_slug', models.SlugField(max_length=255, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('country_slug', models.SlugField(max_length=255)),
                ('country', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Main_Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
            ],
            options={
                'verbose_name_plural': 'Main_Categories',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='products.main_categories')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('torgsoft_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('barcode', models.CharField(blank=True, max_length=128, null=True)),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=64, verbose_name='Артикул')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('weight', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Вага (г)')),
                ('color', models.CharField(blank=True, max_length=32, null=True, verbose_name='Колір')),
                ('size', models.CharField(blank=True, max_length=32, null=True, verbose_name='Розмір')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('prime_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Собівартість')),
                ('retail_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Ціна роздрібна')),
                ('wholesale_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Оптова ціна')),
                ('retail_price_with_discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Ціна роздрібна зі знижкою')),
                ('warehouse_quantity', models.IntegerField(default=0, verbose_name='Наявність')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('torgsoft_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('barcode', models.CharField(blank=True, max_length=128, null=True)),
                ('sku', models.CharField(max_length=255, verbose_name='Артикул')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('weight', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Вага (г)')),
                ('color', models.CharField(blank=True, max_length=32, null=True, verbose_name='Колір')),
                ('size', models.CharField(blank=True, max_length=32, null=True, verbose_name='Розмір')),
                ('prime_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Собівартість')),
                ('retail_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Ціна роздрібна')),
                ('wholesale_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Оптова ціна')),
                ('retail_price_with_discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Ціна роздрібна зі знижкою')),
                ('warehouse_quantity', models.IntegerField(default=0, verbose_name='Наявність')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
            ],
            options={
                'verbose_name': 'Варіант товару',
                'verbose_name_plural': 'Варіанти товарів',
                'ordering': ['product', 'sku'],
            },
        ),
        migrations.CreateModel(
            name='PopularProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0, help_text='Чим менше — тим вище')),
                ('is_active', models.BooleanField(default=True)),
                ('label', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='popular', to='products.product')),
            ],
            options={
                'verbose_name': 'Популярний товар',
                'verbose_name_plural': 'Популярні товари',
                'db_table': 'products_popular',
                'ordering': ['position', '-created_at'],
                'indexes': [models.Index(fields=['is_active', 'position'], name='products_po_is_acti_4ac398_idx')],
            },
        ),
    ]
