# Generated by Django 5.1.11 on 2025-08-30 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TSGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('good_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=128, null=True)),
                ('articul', models.CharField(blank=True, max_length=128, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('display', models.CharField(blank=True, max_length=32, null=True)),
                ('the_size', models.CharField(blank=True, max_length=64, null=True)),
                ('color', models.CharField(blank=True, max_length=64, null=True)),
                ('material', models.CharField(blank=True, max_length=128, null=True)),
                ('fashion_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sex', models.CharField(blank=True, max_length=16, null=True)),
                ('short_name', models.CharField(blank=True, max_length=255, null=True)),
                ('good_type_full', models.CharField(blank=True, max_length=255, null=True)),
                ('producer_collection_full', models.CharField(blank=True, max_length=255, null=True)),
                ('season', models.CharField(blank=True, max_length=64, null=True)),
                ('barcode', models.CharField(blank=True, max_length=255, null=True)),
                ('pack', models.CharField(blank=True, max_length=64, null=True)),
                ('pack_size', models.CharField(blank=True, max_length=64, null=True)),
                ('power_supply', models.CharField(blank=True, max_length=64, null=True)),
                ('age', models.CharField(blank=True, max_length=64, null=True)),
                ('measure', models.CharField(blank=True, max_length=64, null=True)),
                ('measure_unit', models.CharField(blank=True, max_length=32, null=True)),
                ('equal_currency_name', models.CharField(blank=True, max_length=32, null=True)),
                ('supplier_code', models.CharField(blank=True, max_length=64, null=True)),
                ('analogs', models.TextField(blank=True, null=True)),
                ('retail_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('wholesale_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('retail_price_with_discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('min_quantity_for_order', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('height', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('width', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('warehouse_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('count_units_per_box', models.IntegerField(default=0)),
                ('closeout', models.BooleanField(default=False)),
                ('retail_price_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('wholesale_price_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('equal_sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('equal_wholesale_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('prime_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'TSGoods (сирі дані Торгсофт)',
                'verbose_name_plural': 'TSGoods (сирі дані Торгсофт)',
                'db_table': 'ts_goods',
            },
        ),
    ]
